
export const testingConsts = {

    repos :[
        {
          "id": 336777,
          "node_id": "MDEwOlJlcG9zaXRvcnkzMzY3Nzc=",
          "name": "samples",
          "full_name": "angular/samples",
          "private": false,
          "owner": {
            "login": "angular",
            "id": 139426,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTQyNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/139426?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/angular",
            "html_url": "https://github.com/angular",
            "followers_url": "https://api.github.com/users/angular/followers",
            "following_url": "https://api.github.com/users/angular/following{/other_user}",
            "gists_url": "https://api.github.com/users/angular/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/angular/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/angular/subscriptions",
            "organizations_url": "https://api.github.com/users/angular/orgs",
            "repos_url": "https://api.github.com/users/angular/repos",
            "events_url": "https://api.github.com/users/angular/events{/privacy}",
            "received_events_url": "https://api.github.com/users/angular/received_events",
            "type": "Organization",
            "site_admin": false
          },
          "html_url": "https://github.com/angular/samples",
          "description": "DEPRICATED",
          "fork": false,
          "url": "https://api.github.com/repos/angular/samples",
          "forks_url": "https://api.github.com/repos/angular/samples/forks",
          "keys_url": "https://api.github.com/repos/angular/samples/keys{/key_id}",
          "collaborators_url": "https://api.github.com/repos/angular/samples/collaborators{/collaborator}",
          "teams_url": "https://api.github.com/repos/angular/samples/teams",
          "hooks_url": "https://api.github.com/repos/angular/samples/hooks",
          "issue_events_url": "https://api.github.com/repos/angular/samples/issues/events{/number}",
          "events_url": "https://api.github.com/repos/angular/samples/events",
          "assignees_url": "https://api.github.com/repos/angular/samples/assignees{/user}",
          "branches_url": "https://api.github.com/repos/angular/samples/branches{/branch}",
          "tags_url": "https://api.github.com/repos/angular/samples/tags",
          "blobs_url": "https://api.github.com/repos/angular/samples/git/blobs{/sha}",
          "git_tags_url": "https://api.github.com/repos/angular/samples/git/tags{/sha}",
          "git_refs_url": "https://api.github.com/repos/angular/samples/git/refs{/sha}",
          "trees_url": "https://api.github.com/repos/angular/samples/git/trees{/sha}",
          "statuses_url": "https://api.github.com/repos/angular/samples/statuses/{sha}",
          "languages_url": "https://api.github.com/repos/angular/samples/languages",
          "stargazers_url": "https://api.github.com/repos/angular/samples/stargazers",
          "contributors_url": "https://api.github.com/repos/angular/samples/contributors",
          "subscribers_url": "https://api.github.com/repos/angular/samples/subscribers",
          "subscription_url": "https://api.github.com/repos/angular/samples/subscription",
          "commits_url": "https://api.github.com/repos/angular/samples/commits{/sha}",
          "git_commits_url": "https://api.github.com/repos/angular/samples/git/commits{/sha}",
          "comments_url": "https://api.github.com/repos/angular/samples/comments{/number}",
          "issue_comment_url": "https://api.github.com/repos/angular/samples/issues/comments{/number}",
          "contents_url": "https://api.github.com/repos/angular/samples/contents/{+path}",
          "compare_url": "https://api.github.com/repos/angular/samples/compare/{base}...{head}",
          "merges_url": "https://api.github.com/repos/angular/samples/merges",
          "archive_url": "https://api.github.com/repos/angular/samples/{archive_format}{/ref}",
          "downloads_url": "https://api.github.com/repos/angular/samples/downloads",
          "issues_url": "https://api.github.com/repos/angular/samples/issues{/number}",
          "pulls_url": "https://api.github.com/repos/angular/samples/pulls{/number}",
          "milestones_url": "https://api.github.com/repos/angular/samples/milestones{/number}",
          "notifications_url": "https://api.github.com/repos/angular/samples/notifications{?since,all,participating}",
          "labels_url": "https://api.github.com/repos/angular/samples/labels{/name}",
          "releases_url": "https://api.github.com/repos/angular/samples/releases{/id}",
          "deployments_url": "https://api.github.com/repos/angular/samples/deployments",
          "created_at": "2009-10-14T04:35:36Z",
          "updated_at": "2021-11-08T09:44:15Z",
          "pushed_at": "2010-01-14T00:09:02Z",
          "git_url": "git://github.com/angular/samples.git",
          "ssh_url": "git@github.com:angular/samples.git",
          "clone_url": "https://github.com/angular/samples.git",
          "svn_url": "https://github.com/angular/samples",
          "homepage": "http://www.getangular.com",
          "size": 93,
          "stargazers_count": 3,
          "watchers_count": 3,
          "language": "Ruby",
          "has_issues": true,
          "has_projects": true,
          "has_downloads": true,
          "has_wiki": true,
          "has_pages": true,
          "forks_count": 13,
          "mirror_url": null,
          "archived": true,
          "disabled": false,
          "open_issues_count": 0,
          "license": null,
          "allow_forking": true,
          "is_template": false,
          "topics": [],
          "visibility": "public",
          "forks": 13,
          "open_issues": 0,
          "watchers": 3,
          "default_branch": "master",
          "permissions": {
            "admin": false,
            "maintain": false,
            "push": false,
            "triage": false,
            "pull": true
          }
        },
    ],
    link: '<https://api.github.com/organizations/139426/repos?per_page=100&page=1>; rel="next", <https://api.github.com/organizations/139416/repos?per_page=100&page=1>; rel="last"',
    page: 1,
    repo_fullname: 'angular/samples',
    repo_name: 'samples',
    contributors:
    [
        {
          "login": "abrons",
          "id": 4529,
          "node_id": "MDQ6VXNlcjQ1Mjk=",
          "avatar_url": "https://avatars.githubusercontent.com/u/4529?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/abrons",
          "html_url": "https://github.com/abrons",
          "followers_url": "https://api.github.com/users/abrons/followers",
          "following_url": "https://api.github.com/users/abrons/following{/other_user}",
          "gists_url": "https://api.github.com/users/abrons/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/abrons/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/abrons/subscriptions",
          "organizations_url": "https://api.github.com/users/abrons/orgs",
          "repos_url": "https://api.github.com/users/abrons/repos",
          "events_url": "https://api.github.com/users/abrons/events{/privacy}",
          "received_events_url": "https://api.github.com/users/abrons/received_events",
          "type": "User",
          "site_admin": false,
          "contributions": 4
        }
      ], 
      username: 'abrons', 
      userDetails: {
        "login": "abrons",
        "id": 4529,
        "node_id": "MDQ6VXNlcjQ1Mjk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4529?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/abrons",
        "html_url": "https://github.com/abrons",
        "followers_url": "https://api.github.com/users/abrons/followers",
        "following_url": "https://api.github.com/users/abrons/following{/other_user}",
        "gists_url": "https://api.github.com/users/abrons/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/abrons/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/abrons/subscriptions",
        "organizations_url": "https://api.github.com/users/abrons/orgs",
        "repos_url": "https://api.github.com/users/abrons/repos",
        "events_url": "https://api.github.com/users/abrons/events{/privacy}",
        "received_events_url": "https://api.github.com/users/abrons/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Adam Abrons",
        "company": "@ConsultingMD ",
        "blog": "https://www.grandrounds.com",
        "location": "Alameda, CA",
        "email": null,
        "hireable": null,
        "bio": null,
        "twitter_username": null,
        "public_repos": 11,
        "public_gists": 2,
        "followers": 94,
        "following": 11,
        "created_at": "2008-04-03T16:31:42Z",
        "updated_at": "2021-10-19T01:57:08Z"
      },
      userWithContributions: {
        "contributions": 4,
        "login": "abrons",
        "id": 4529,
        "node_id": "MDQ6VXNlcjQ1Mjk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4529?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/abrons",
        "html_url": "https://github.com/abrons",
        "followers_url": "https://api.github.com/users/abrons/followers",
        "following_url": "https://api.github.com/users/abrons/following{/other_user}",
        "gists_url": "https://api.github.com/users/abrons/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/abrons/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/abrons/subscriptions",
        "organizations_url": "https://api.github.com/users/abrons/orgs",
        "repos_url": "https://api.github.com/users/abrons/repos",
        "events_url": "https://api.github.com/users/abrons/events{/privacy}",
        "received_events_url": "https://api.github.com/users/abrons/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Adam Abrons",
        "company": "@ConsultingMD ",
        "blog": "https://www.grandrounds.com",
        "location": "Alameda, CA",
        "email": null,
        "hireable": null,
        "bio": null,
        "twitter_username": null,
        "public_repos": 11,
        "public_gists": 2,
        "followers": 94,
        "following": 11,
        "created_at": "2008-04-03T16:31:42Z",
        "updated_at": "2021-10-19T01:57:08Z"
      }
      
      
}